language: node_js
node_js: lts/*

addons:
  apt:
    update: true
    packages:
    - libappindicator1
    - fonts-liberation
    - google-chrome-stable

before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install: true

script:
- npm i
- npm update
- npm run build
- npm run ghpages
- npm run compile
- if [ -f npm-debug.log ]; then cat npm-debug.log; fi

cache:
  directories:
  - node_modules
