version: '2'
services:
  nginx:
    container_name: nginx-react
    image: nginx:1.10.3-alpine
    volumes:
      - 'nginx-volume:/var/log/nginx'
      - '../dist:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"
    networks:
      - external-network
networks:
  external-network:
    driver: bridge
volumes:
  nginx-volume:
    driver: local
